---
title: "Correct SASP Values"
author: "Danielle Reimanis"
date: "1/22/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(tidyr)
library(lubridate)
library(ggthemes)
library(ggpubr)
library(ggplot2)
library(stringr)
library(purrr)

```

Workable Data Sets

```{r}
# sasp_og <- read.csv('data/SASP_1hr.csv')
# sbsp_og <- read.csv('data/SBSP_1hr.csv')
# 
# sbsp <- sbsp_og   %>%
#   mutate(., Date = mdy(Date))%>%
#   mutate(., Hour0 = ifelse(nchar(Hour) < 4,
#                           paste0("0", Hour), Hour))%>%
#   rename("date" = Date)%>%
#   mutate(., datetime_test = paste(date, Hour0, sep = " "),
#          datetime = ymd_hm(datetime_test, tz = "MST"))%>%
#   filter(datetime >= "2005-01-20 12:00:00")%>%
#   select(51,4,3,2,5,6,8,10,14,20,23:27,29,35,44,46,48)
# 
# save(sbsp, file = "data/sbsp.Rdata")
# 
# sasp <- sasp_og   %>%
#   mutate(., Date = mdy(Date))%>%
#   mutate(., Hour0 = ifelse(nchar(Hour) < 4,
#                           paste0("0", Hour), Hour))%>%
#   rename("date" = Date)%>%
#   mutate(., datetime_test = paste(date, Hour0, sep = " "),
#          datetime = ymd_hm(datetime_test, tz = "MST"))%>%
#   filter(datetime >= "2005-01-25 12:00:00")%>%
#   select(37,4,3,2,5,6,8,10,14,17:21, 23,29,32,32)
# 
# save(sasp, file = "data/sasp.Rdata")

load("data/sasp.Rdata")
load("data/sbsp.Rdata")

```


SBSP and SASP Changes in Hkin 
```{r}
hist(sasp_filtered$PyUp_Unfilt_W)
hist(sbsp_filtered$PyUp_Unfilt_W)
hist(sasp_filtered$PyUp_Filt_W)
hist(sbsp_filtered$PyUp_Filt_W)

sasp_filtered <- sasp%>%
  filter(PyUp_Unfilt_W > 0)%>%
  filter(Hour == 1200)

sbsp_filtered <- sbsp%>%
  filter(PyUp_Unfilt_W > 0)%>%
  filter(Hour == 1200)

sbsp_pyup_unfilt <- sbsp_filtered%>%
  select(1, 13:15)%>%
  rename("PyUp_Unfilt_SBSP" = 2,
         "PyUp_Filt_SBSP" = 3,
         "PyUp_Shad_SBSP" = 4)

sasp_sbsp_boxplot <- sasp_filtered%>%
  merge(., sbsp_pyup_unfilt, by = "datetime", all= TRUE)%>%
  filter(PyUp_Shad_W > 0)%>%
  select(1,12:14,18:20)

ggplot(sasp_sbsp_boxplot, aes(x=datetime))+
  geom_point(aes(y=PyUp_Unfilt_SBSP), color = "blue")+
  geom_point(aes(y=PyUp_Unfilt_W), color = "lightblue")

ggplot(sasp_sbsp_boxplot, aes(x=PyUp_Unfilt_SBSP, y=PyUp_Unfilt_W))+
  geom_point(color = "goldenrod")+
  theme_bw()+
  labs(x="PyUp Unfiltered SBSP (W)", y="PyUp Unfiltered SASP (W)")+
  geom_abline()

ggplot(sasp_sbsp_boxplot, aes(x=PyUp_Filt_SBSP, y=PyUp_Filt_W))+
  geom_point(color = "indianred4")+
  theme_bw()+
  labs(x="PyUp Filtered SBSP (W)", y="PyUp Filtered SASP (W)")+
  geom_abline()

ggplot(sasp_sbsp_boxplot, aes(x=PyUp_Shad_SBSP, y=PyUp_Shad_W))+
  geom_point(color = "olivedrab4")+
  theme_bw()+
  labs(x="PyUp Shade SBSP (W)", y="PyUp Shade SASP (W)")+
  geom_abline()

sasp_sbsp_boxplot_long <- sasp_sbsp_boxplot%>%
  rename("SASP_Unfilt" =2,
         "SASP_Filt" =3,
         "SASP_Shad" = 4,
         "SBSP_Unfilt" = 5,
         "SBSP_Filt" = 6,
         "SBSP_Shad" = 7)%>%
  gather(., key = "specific", value = "incoming_radiation", -datetime)

sasp_sbsp_boxplot_long$specific <- factor(sasp_sbsp_boxplot_long$specific, 
                                      levels = c("SASP_Unfilt","SASP_Filt","SASP_Shad",
                                                 "SBSP_Unfilt","SBSP_Filt","SBSP_Shad"))

sasp_sbsp_boxplot_long <- sasp_sbsp_boxplot_long%>%
  mutate(site = ifelse(substr(specific,1,4) == "SASP", "SASP", "SBSP"),
         type = str_sub(specific, 6, -1))

ggplot(sasp_sbsp_boxplot_long, aes(x=datetime, y=incoming_radiation, 
                                   group = site, color=site))+
  geom_point(aes(shape = type), size = 1)+
  scale_color_manual(values = c("burlywood", "olivedrab4"))

  
```

Correcting SASP Values
```{r}
unfilt_box <- sasp_sbsp_boxplot%>%
  select(1,2,5)%>%
  rename("SASP_Unfilt" = 2,
         "SBSP_Unfilt" = 3)%>%
  gather(., key = "site", value = "Hkin", -datetime)

boxplot(Hkin~site, data = unfilt_box)

```

### Importing Skiles data
```{r}

skiles_files <- list.files('data/Skiles_Data', full.names = TRUE)
  
skiles_reader <- function(file){
  data_names = str_sub(file, -8,-5)
  name = paste("WY", data_names, sep = "")
  df <- read_delim(file= file,
                        delim = " ", col_names = FALSE)%>%
  select(1:17)%>%
  rename("year" = 1, "month" = 2, "day" = 3, "hour" = 4, "doy" = 5,
         "hkin_unfilt" = 6, "hkout_unfilt" = 7, "hkabs_unfilt" = 8, "alb_unfilt" = 9,
         "hkin_filt" = 10, "hkout_filt" = 11, "hkabs_filt" = 12, "alb_filt" = 13,
         "hkin_shad" = 14, "hkout_shad" = 15, "hkabs_shad" = 16, "alb_shad" = 17)%>%
  mutate_if(is.character, as.numeric)%>%
  mutate(date = paste(month, day, year, sep = " "),
         date = mdy(date))%>%
  mutate(WY = name)%>%
  select(18:19, 4:17)%>%
  mutate_all(funs(replace(., .<0,NA)))
  
  return(df)
}

sasp_05_14_skiles <- map_dfr(skiles_files, skiles_reader)

  
```

Noon Values

```{r}
sasp_05_14_skiles_noon <- sasp_05_14_skiles%>%
  filter(hour == 12,
         date > "2005-01-24")
  
ggplot(sasp_05_14_skiles_noon, aes(x=date, y=alb_unfilt))+
  geom_line()
ggplot(sasp_05_14_skiles_noon, aes(x=date, y=hkin_unfilt))+
  geom_point()
ggplot(sasp_05_14_skiles_noon, aes(x=date, y=hkout_unfilt))+
  geom_point()

sasp_noon <- sasp%>%
  filter(Hour == 1200)%>%
  filter(date < "2014-09-30")%>%
  select(2,10,12)%>%
  rename("hkin_obs" = 3,
         "hkout_obs" = 2)%>%
  mutate_all(funs(replace(., .<0,NA)))

doy_factor <- 
  
sasp_Skiles_obs <- sasp_05_14_skiles_noon %>%
  select(1, 2, 4, 5, 6)%>%
  merge(., sasp_noon, by = "date")%>%
  mutate(wy_doy = ifelse(doy > 273, doy-273, doy+92))

ggplot(sasp_Skiles_obs, aes(x=hkin_obs, y=hkin_unfilt))+
  geom_point()+
  geom_abline()+
  theme_bw()+
  facet_wrap(~WY)
ggplot(sasp_Skiles_obs, aes(x=hkout_obs, y=hkout_unfilt))+
  geom_point()+
  geom_abline()+
  theme_bw()+
  facet_wrap(~WY)
ggplot(sasp_Skiles_obs, aes(x=doy))+
  geom_point(aes(y=hkout_unfilt), color = "lightblue3")+
  geom_point(aes(y=hkout_obs), color = "lightblue4")+
  facet_wrap(~WY)+
  theme_bw()
ggplot(sasp_Skiles_obs, aes(x=doy))+
  geom_point(aes(y=hkin_unfilt), color = "gray")+
  geom_point(aes(y=hkin_obs), color = "gray17")+
  facet_wrap(~WY)+
  theme_bw()

hkin_long <- sasp_Skiles_obs%>%
  select(1:4,7,8)%>%
  rename("calculated" = 4,
         "observed" = 5)%>%
  gather(., key = "type", value = "hkin", -date, -WY, -doy, -wy_doy)

ggplot(hkin_long, aes(x=wy_doy, y=hkin, color = type))+
  geom_line()+
  facet_wrap(~WY)+
  theme_bw()+
  scale_color_manual(values = c("gray17","gray"))

ggplot(hkin_long, aes(x=wy_doy, y=hkin, color = type))+
  geom_line()+
  facet_wrap(~WY)+
  theme_bw()+
  scale_color_manual(values = c("gray17","gray"))+
  geom_vline(xintercept = 274)

hkout_long <- sasp_Skiles_obs%>%
  select(1:3,5,6,8)%>%
  rename("calculated" = 4,
         "observed" = 5)%>%
  gather(., key = "type", value = "hkout", -date, -WY, -doy, -wy_doy)

ggplot(hkout_long, aes(x=wy_doy, y=hkout, color = type))+
  geom_line()+
  facet_wrap(~WY)+
  theme_bw()+
  scale_color_manual(values = c("blueviolet","lightblue4"))

boxplot(hkout~type, data = hkout_long)
boxplot(hkin~type, data = hkin_long)

```

### Skiles Depth Write In

```{r}
skiles_depth <- list.files('data/Skiles_Depth', full.names = TRUE)

depth_reader <- function(file){
  data_year = str_sub(file, -18, -15)
  name = paste("WY", data_year, sep = "")
  df <- read_delim(file = file,
                            delim = " ", col_names=FALSE)%>%
    rename("year" =1, "month" = 2, "day" = 3, 
           "hour" = 4, "doy" = 5, "depth_m" =6)%>%
    mutate_if(is.character, as.numeric)%>%
    mutate(date = paste(month, day, year, sep = " "),
         date = mdy(date))%>%
    mutate(WY = name)%>%
    select(7,8,4,5,6)%>%
    mutate_all(funs(replace(., .<0,NA)))%>%
    mutate(depth_m = ifelse(depth_m > 9000, NA, depth_m))
         
   return(df)
}
  
sasp_05_14_depth_skiles <- map_dfr(skiles_depth, depth_reader)

```

Observed Depth and Calculated Depth
```{r}

ggplot(sasp_05_14_depth_skiles, aes(x=date, y=depth_m))+
  geom_line()

sasp_depth_noon <- sasp%>%
  filter(Hour == 1200)%>%
  select(2,16)%>%
  rename(observed_m = 2)

sasp_05_14_depth_noon <- sasp_05_14_depth_skiles%>%
  filter(hour == 12)%>%
  rename(calculated_m = 5)%>%
  merge(., sasp_depth_noon, by = 'date')%>%
  mutate(diff = calculated_m - observed_m)%>%
  filter(diff > -0.25)%>%
  mutate(correct_m = ifelse(is.na(observed_m), calculated_m, observed_m),
         correct_m = ifelse(is.na(correct_m), observed_m, calculated_m))%>%
  mutate(diff_correct = correct_m - observed_m)%>%
  mutate(wy_doy = ifelse(doy > 273, doy-273, doy+92))

ggplot(sasp_05_14_depth_noon, aes(x=observed_m, y=calculated_m))+
  geom_point()
ggplot(sasp_05_14_depth_noon, aes(x=doy, y=diff))+
  geom_point()
ggplot(sasp_05_14_depth_noon, aes(x=observed_m, y=correct_m))+
  geom_point()
ggplot(sasp_05_14_depth_noon, aes(x=doy, y=diff_correct))+
  geom_point()

ggplot(sasp_05_14_depth_noon, aes(x=date))+
  geom_point(aes(y=calculated_m), color = "black")+
  geom_point(aes(y=observed_m), color = "darkolivegreen")+
  geom_point(aes(y=correct_m), color = "goldenrod4", size =0.5)

```

Usable depth dataframe
```{r}
sasp_depth_05_14 <- sasp_05_14_depth_noon%>%
  select(1,2,10,4,8)%>%
  rename("depth_m" = 5)

ggplot(sasp_depth_05_14, aes(x=wy_doy, y=depth_m))+
  geom_line()+
  facet_wrap(~WY)+
  theme_bw()+
  labs(x = "Day of Water Year", y= "Depth of Snowpack (m)")

```

Usable Hkin dataframe
```{r}

names(sasp_Skiles_obs)
names(sasp_hkin_05_14)
sasp_hkin_05_14 <- sasp_Skiles_obs %>%
  select(1,2,8,4,7)
  

```

