---
title: "Winter Seasons (2017-2019)"
author: "Danielle Reimanis"
date: "10/15/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(ggplot2)
library(tidyr)
library(lubridate)
library(darksky)
library(xts)
library(dygraphs)
library(ggthemes)
library(suncalc)
library(RNRCS)


```

Organizing the data - August 2017 - August 2019
(SASP, SBSP, Red Mountain Pass SNOTEL, sunlight data)

```{r}
sasp_og <- read.csv('data/SASP_1hr.csv')
sbsp_og <- read.csv('data/SBSP_1hr.csv')
red_mtn_pass <- grabNRCS.data(network = 'SNTL', site_id  = '713',
                              timescale = 'daily',
                                DayBgn = '2017-08-01', DayEnd = '2019-07-31')


date <- seq.Date(from = as.Date("2017-08-01", tz = "MST"), 
                 to = as.Date("2019-07-31", tz = "MST"), 
                 by = 1)

sunlight_data <- getSunlightTimes(date = date,
                                  lat = 37.9, 
                                  lon = -107.7, 
                                  tz = "MST", 
                                  keep = c("sunrise", "solarNoon", "sunset"))

sbsp <- sbsp_og   %>%
  mutate(., Date = mdy(Date))%>%
  mutate(., Hour0 = ifelse(nchar(Hour) < 4, 
                          paste0("0", Hour), Hour))%>%
  rename("date" = Date)%>%
  mutate(., datetime_test = paste(date, Hour0, sep = " "),
         datetime = ymd_hm(datetime_test, tz = "MST"))%>%
  filter(datetime >= "2017-08-01 01:00:00")%>%
  filter(datetime <= "2019-08-01 00:00:00")

sasp <- sasp_og %>%
  mutate(., Date = mdy(Date))%>%
  mutate(., Hour0 = ifelse(nchar(Hour) < 4, 
                          paste0("0", Hour), Hour))%>%
  rename("date" = Date)%>%
  mutate(., datetime_test = paste(date, Hour0, sep = " "),
         datetime = ymd_hm(datetime_test, tz = "MST"))%>%
  filter(datetime >= "2017-08-01 01:00:00")%>%
  filter(datetime <= "2019-08-01 00:00:00")

# Datetimes do not match starting 2019-08-13, therefore I am removing all days after 07/31/202 at midnight This analysis was done and then I went back to change the code above. It will not work now because all values are TRUE.
# 
# datetime_sasp <- sasp$datetime
# datetime_sbsp <- sbsp$datetime
# 
# datetime_confirmation <- data.frame(sbsp = datetime_sbsp, sasp = datetime_sasp)%>%
#   mutate(check = ifelse(datetime_sasp == datetime_sbsp, "TRUE", "FALSE"))%>%
#   filter(check == "FALSE")


sbsp_sunlight_combined <- sunlight_data %>%
  mutate(sunrise = as.POSIXct(sunrise),
         sunset = as.POSIXct(sunset))%>%
  inner_join(sbsp, by = 'date')%>%
  mutate(day_night = ifelse(datetime > sunrise &
                              datetime < sunset, 'day', 'night'))%>%
  mutate(noon_time = format(solarNoon, "%H:%M:%S"))%>%
  mutate(noon = ifelse(hour(datetime) == hour(solarNoon), 'noon', 'NA'))

sasp_sunlight_combined <- sunlight_data %>%
  mutate(sunrise = as.POSIXct(sunrise),
         sunset = as.POSIXct(sunset))%>%
  inner_join(sasp, by = 'date')%>%
  mutate(day_night = ifelse(datetime > sunrise &
                              datetime < sunset, 'day', 'night'))%>%
  mutate(noon_time = format(solarNoon, "%H:%M:%S"))%>%
  mutate(noon = ifelse(hour(datetime) == hour(solarNoon), 'noon', 'NA'))

sbsp_noon <- sbsp_sunlight_combined%>%
  filter(noon == "noon")

sasp_noon <- sasp_sunlight_combined%>%
  filter(noon == "noon")

```

Versgehy 1991 albedo model on 2017-2018
```{r}

red_mtn_pass_assumed_snow_2017_18 <- red_mtn_pass %>%
  select(1:4, 6:8)%>%
  rename("date" = 1,
         "temp_avg_F" = 2,
         "temp_max_F" = 3,
         "temp_min_F" = 4,
         "precip_accum_in" = 5,
         "snow_depth_in" = 6,
         "SWE_in" = 7)%>%
  filter(date < "2018-07-01")%>%
  mutate(snow_accum = snow_depth_in - lag(snow_depth_in),
         snow_accum_pos = ifelse(snow_accum < 0, 0, snow_accum),
         temp_avg_C = ((temp_avg_F - 32)*(5/9)))%>%
  mutate(date = ymd(date))

albedo_df_test_17 <- red_mtn_pass_assumed_snow_2017_18 %>%
  filter(!is.na(snow_accum),
         !is.na(snow_accum_pos))%>%
  mutate(bare_albedo = 0.25,
         cume_snow = cumsum(snow_accum_pos),
         fresh_albedo = ifelse(snow_accum_pos > 0, 0.84, NA),
         albedo_min = ifelse(temp_avg_C < 0 & snow_accum_pos == 0, 0.7, 
                             ifelse(temp_avg_C >= 0, 0.5, NA)),
         albedo_min = ifelse(temp_avg_C > 0 & cume_snow == lag(cume_snow), 
                             0.25, albedo_min))%>%
  mutate(actual_albedo = ifelse(cume_snow == 0,bare_albedo,NA),
         actual_albedo = ifelse(snow_accum_pos > 0, 0.84, actual_albedo),
         actual_albedo = ifelse(snow_depth_in == 0, 0.25, actual_albedo))
         
albedo = albedo_df_test_17$actual_albedo

for(i in 1:nrow(albedo_df_test_17)){
  if(is.na(albedo[i])){
    albedo[i] = ((albedo[i-1]*exp(-0.01)))
  }
}

albedo_df_test_17$actual_albedo <- albedo

ggplot(albedo_df_test_17,aes(x=date,y=actual_albedo)) +
  geom_line()+
  theme_bw()+
  labs(x='Day', y='Albedo')

```

Versgehy 1991 albedo model on 2018-2019

```{r}

red_mtn_pass_assumed_snow_2018_19 <- red_mtn_pass %>%
  select(1:4, 6:8)%>%
  rename("date" = 1,
         "temp_avg_F" = 2,
         "temp_max_F" = 3,
         "temp_min_F" = 4,
         "precip_accum_in" = 5,
         "snow_depth_in" = 6,
         "SWE_in" = 7)%>%
  filter(date > "2018-09-01")%>%
  mutate(snow_accum = snow_depth_in - lag(snow_depth_in),
         snow_accum_pos = ifelse(snow_accum < 0, 0, snow_accum),
         temp_avg_C = ((temp_avg_F - 32)*(5/9)))%>%
  mutate(date = ymd(date))

albedo_df_test_18 <- red_mtn_pass_assumed_snow_2018_19 %>%
  filter(!is.na(snow_accum),
         !is.na(snow_accum_pos))%>%
  mutate(bare_albedo = 0.25,
         cume_snow = cumsum(snow_accum_pos),
         fresh_albedo = ifelse(snow_accum_pos > 0, 0.84, NA),
         albedo_min = ifelse(temp_avg_C < 0 & snow_accum_pos == 0, 0.7, 
                             ifelse(temp_avg_C >= 0, 0.5, NA)),
         albedo_min = ifelse(temp_avg_C > 0 & cume_snow == lag(cume_snow), 
                             0.25, albedo_min))%>%
  mutate(actual_albedo = ifelse(cume_snow == 0,bare_albedo,NA),
         actual_albedo = ifelse(snow_accum_pos > 0, 0.84, actual_albedo),
         actual_albedo = ifelse(snow_depth_in == 0, 0.25, actual_albedo))
         
albedo = albedo_df_test_18$actual_albedo

for(i in 1:nrow(albedo_df_test_18)){
  if(is.na(albedo[i])){
    albedo[i] = ((albedo[i-1]*exp(-0.01)))
  }
}

albedo_df_test_18$actual_albedo <- albedo

ggplot(albedo_df_test_18,aes(x=date,y=actual_albedo)) +
  geom_line()+
  theme_bw()+
  labs(x='Day', y='Albedo')


```

