---
title: "Waterloo Analysis"
author: "Danielle Reimanis"
date: "2/22/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(tidyr)
library(lubridate)
library(ggthemes)
library(ggpubr)
library(ggplot2)
library(stringr)
library(purrr)
library(xts)
library(dygraphs)

```

### Waterloo Depth Read In
```{r}

wtrloo_depth_files <- list.files('data/WtrLoo_depth', full.names=T)

wtrloo_depth_function <- function(file){
  df <- read_csv(file, col_names = T)%>%
    rename("date" = Date,
           "DOY" = 2,
           "depth_cm" = 3)%>%
    mutate(depth_cm = ifelse(depth_cm == "Trace", 0.2, depth_cm))%>%
    mutate(date = dmy(date),
           depth_cm = as.numeric(depth_cm))
return(df)
}

wtrloo_depth <- map_dfr(wtrloo_depth_files, wtrloo_depth_function)

wtrloo_depth_all <- seq.Date(from = as.Date("2005-09-01"), 
                        to = as.Date("2013-07-01"), by = "day")%>%
  as.data.frame()%>%
  rename("date" =1)%>%
  merge(., wtrloo_depth, by ="date", all=T)%>%
  mutate(depth_cm = ifelse(is.na(depth_cm), 0, depth_cm))%>%
  select(1,3)

```

### Waterloo Met Read In
```{r}
sn <- read_csv(file="data/Solarnoon_1year.csv")
wtrloo_met_files <- list.files('data/WtrLoo_Met', full.names=T)

wtrloo_met_function <- function(file){
df <- read_csv(file = file, col_names = T)%>%
  select(2,3,4,7,8,9,10,11,12,13)%>%
  mutate(minute = str_sub(Time, -2,-1),
         hour = str_sub(Time, -4,-3),
         hour = ifelse(hour == "", 0, hour))%>%
  rename("year" =1, "DOY" = 2)%>%
  mutate(datetime_raw = paste(year, DOY, hour, minute),
         datetime = strptime(datetime_raw, "%Y %j %H %M"),
         date = as.Date(datetime_raw, "%Y %j"))%>%
  mutate(time = substr(as.POSIXct(sprintf("%04.0f", Time), format = "%H%M"),  12, 19))%>%
  filter(time %in% c("11:45:00","12:00:00","12:15:00"))%>%
  merge(., sn, by = "DOY")%>%
  mutate(SolarNoon = as.character(SolarNoon))%>%
  mutate(sn_minute = str_sub(SolarNoon, 4,5),
         time_minute = str_sub(time, 4,5),
         sn_minute = as.numeric(sn_minute),
         time_minute = as.numeric(time_minute),
         sn_minute = sn_minute/60,
         time_minute = time_minute/60,
         sn_minute = as.numeric(str_sub(SolarNoon, 1,2))+sn_minute,
         time_minute = as.numeric(str_sub(time, 1,2))+time_minute,
         time_diff = abs(time_minute - sn_minute))%>%
  group_by(DOY)%>%
  mutate(min_diff = min(time_diff))%>%
  mutate(min_diff_filt = ifelse(min_diff == time_diff, 1, 0))%>%
  filter(min_diff_filt == 1)%>%
  select(1:2, 4:10,15,16,17)%>%
  select(10,1,2,11,12,3:9)%>%
  rename("Hkin" = 6,
         "Hkout" = 7,
         "RH" = 8,
         "Ta" = 9, 
         "Pa" = 10,
         "Udir" = 11,
         "Uz" = 12)%>%
  mutate(albedo = Hkout/Hkin)

return(df)
}

wtrloo_met_data <- map_dfr(wtrloo_met_files, wtrloo_met_function)%>%
  filter(date >= "2005-09-01" & date <= "2013-08-31")

```

### Joined Met and Deoth, WtrLoo
```{r}
wtrloo_depth_met <- wtrloo_depth_all%>%
  merge(., wtrloo_met_data, by = "date", all = T)%>%
  mutate(SY = ifelse(date >= "2005-09-01" & date < "2006-09-01", "SY2006",
              ifelse(date >= "2006-09-01" & date < "2007-09-01", "SY2007",
              ifelse(date >= "2007-09-01" & date < "2008-09-01", "SY2008",
              ifelse(date >= "2008-09-01" & date < "2009-09-01", "SY2009",
              ifelse(date >= "2009-09-01" & date < "2010-09-01", "SY2010",
              ifelse(date >= "2010-09-01" & date < "2011-09-01", "SY2011",
              ifelse(date >= "2011-09-01" & date < "2012-09-01", "SY2012",                                        ifelse(date >= "2012-09-01" & date < "2013-09-01", "SY2013",NA)))))))))%>%
  mutate(DOSY = ifelse(DOY > 243, DOY-243, DOY+122),
         DOSY = ifelse(SY == "SY2009", ifelse(DOY > 244, DOY-244, DOY+122), DOSY),
         DOSY = ifelse(SY == "SY2013", ifelse(DOY > 244, DOY-244, DOY+122), DOSY))%>%
  filter(!is.na(SY))

```

### Early plots
```{r}
ggplot(wtrloo_depth_met%>%filter(albedo<1 & albedo>0 & DOSY < 250), aes(x=DOSY))+
  geom_line(aes(y=albedo), color = "indianred2")+
  geom_line(aes(y=depth_cm/30), color = "steelblue3")+
  facet_wrap(~SY, ncol = 2)+
  theme_bw()+
  scale_y_continuous(name = "Albedo",
                     sec.axis = sec_axis(~.*30, name = "Depth (cm)"))+
   labs(title= "University of Waterloo Albedo vs Depth, SY(9/1-8/31)")

ggplot(wtrloo_depth_met%>%filter(albedo<1 & albedo>0 & DOSY < 250), aes(x=depth_cm))+
  geom_point(aes(y=albedo, color = DOSY))+
  facet_wrap(~SY, scales = "free_x")+
  theme_bw()
  
ggplot(wtrloo_depth_met%>%filter(depth_cm >0 & albedo<1 & albedo>0 & DOSY < 250), aes(x=depth_cm))+
  geom_point(aes(y=albedo, color = DOSY))+
  facet_wrap(~SY, scales = "free_x")+
  theme_bw()+
  scale_color_continuous(high = "gray0", low = "snow2")

wtrloo_06_10 <- wtrloo_depth_met%>%
  filter(!SY %in% c("SY2011", "SY2012", "SY2013"))

ggplot(wtrloo_06_10%>%filter(albedo<1 & albedo>0 & DOSY < 250), aes(x=depth_cm))+
  geom_point(aes(y=albedo, color = DOSY))+
  theme_bw()+
  scale_color_continuous(high = "gray0", low = "snow2")
  
```

SY20214
```{r}

```

