---
title: "Marshall Site"
author: "Danielle Reimanis"
date: "3/12/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(tidyr)
library(lubridate)
library(ggthemes)
library(ggpubr)
library(ggplot2)
library(stringr)
library(purrr)
library(xts)
library(dygraphs)

setwd("~/Desktop/Albedo Analysis/albedo-research")
```

### Loading data
```{r}

marshall <-read_table(file = "data/Marshall/marshall_2013-2017.rtf")%>%
  slice(., 35:nrow(marshall))%>%
  rename(x=1)

save(marshall, file = "data/Marshall/marshall.rtf") 

test <- read_delim(file = "data/Marshall/marshall.rtf", delim = ",")
                       
  
mutate(datetime = mdy_hm(datetime))%>%
  mutate(albedo = as.numeric(albedo))

SN <- read_csv("data/Solarnoon_1year.csv", col_names = T)%>%
  mutate(date = seq.Date(from = mdy("1/1/2013"), to = mdy("12/31/2013"), length.out = 365))%>%
  mutate(datetime = paste(date, SolarNoon, sep = " "))%>%
  mutate(datetime = ymd_hms(datetime))%>%
  select(4,1,2)
  
marshall_SN <- marshall%>%
  merge(., SN, by = "datetime", all = T)%>%
  filter(!is.na(SolarNoon))

ggplot(marshall_SN, aes(x=datetime, y=albedo))+
  geom_point()+
  theme_bw()+
  ylim(c(0,1))

snow_dep_long <- marshall_SN%>%
  select(1,15:17)%>%
  rename(North = "dN", East = "dE", West = "dW")%>%
  gather(key = "Location", value = "depth_m", -datetime)

ggplot(snow_dep_long, aes(x=datetime, y=depth_m, shape = Location, color = Location))+
  geom_point()+
  theme_bw()+
  ylab("Depth (meters)")+
  theme(legend.position = c(0.85,0.7))

    
```


### Marshall Simplified
```{r}

marsh <- marshall%>%
  separate(., x, c("datetime","PyUp","PyDwn","PygUp","PygDwn","Tsurf","Hknet","Hlnet","albedo", "Hup", "Hdwn", "Hnet", "TcorrHlUp","TcorrHlDwn","dN","dE","dW"), sep = ",", remove =T)
marsh <- marsh %>%
  mutate(datetime = ymd_hms(datetime))%>%
  mutate(dW = str_sub(dW, 1, 5))%>%
  mutate_if(is.character, as.numeric)%>%
  filter(hour(datetime) %in% c(11,12))

marsh_plot <- marsh %>%
  filter(albedo < 1 & albedo > 0)%>%
  mutate(time = str_sub(datetime, -8,-1))%>%
  mutate(time = hms(time))%>%
  filter(time > hm("11:30") & time < hm("12:30"))

ggplot(marsh_plot, aes(x=datetime, y=albedo))+
  geom_point()+
  facet_wrap(~year(datetime), scales = "free_x")

ggplot(marsh_plot, aes(x=datetime))+
  geom_point(aes(y=dN), color = "black")+
  geom_point(aes(y=dE), color = "red")+
  geom_point(aes(y=dW), color = "blue")+
  facet_wrap(~year(datetime), scales = "free_x")+
  labs(y="depth (meters?)")


```


