---
title: "Waterloo Analysis"
author: "Danielle Reimanis"
date: "2/22/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(tidyr)
library(lubridate)
library(ggthemes)
library(ggpubr)
library(ggplot2)
library(stringr)
library(purrr)
library(xts)
library(dygraphs)
library(suncalc)
library(hms)

```

### Waterloo Depth Read In
```{r}

wtrloo_depth_files <- list.files('data/WtrLoo_depth', full.names=T)

wtrloo_depth_function <- function(file){
  df <- read_csv(file, col_names = T)%>%
    rename("date" = Date,
           "DOY" = 2,
           "depth_cm" = 3)%>%
    mutate(depth_cm = ifelse(depth_cm == "Trace", 0.2, depth_cm))%>%
    mutate(date = dmy(date),
           depth_cm = as.numeric(depth_cm))
return(df)
}

wtrloo_depth <- map_dfr(wtrloo_depth_files, wtrloo_depth_function)

wtrloo_depth_all <- seq.Date(from = as.Date("2005-09-01"), 
                        to = as.Date("2013-07-01"), by = "day")%>%
  as.data.frame()%>%
  rename("date" =1)%>%
  merge(., wtrloo_depth, by ="date", all=T)%>%
  mutate(depth_cm = ifelse(is.na(depth_cm), 0, depth_cm))%>%
  select(1,3)

```

### Waterloo Solarnoon
```{r}
# Lat = 43.473308
# Long = -80.557102

date <- seq.Date(from = as.Date("2005-09-01", tz = "EST"), 
                 to = as.Date("2015-04-30", tz = "EST"), 
                 by = 1)

sunlight_data <- getSunlightTimes(date = date,
                                  lat = 43.473308,
                                  lon = -80.557102,
                                  tz = "EST", 
                                  keep = c("sunrise", "solarNoon", "sunset"))

SN <- sunlight_data%>%
  select(5)%>%
  mutate(date = date(solarNoon),
         time = as_hms(solarNoon))%>%
  select(2,3)%>%
  as_tibble(.)%>%
  rename(solarNoon = "time")



```
TEST
```{r}
# 
# test <- read_csv(file = "data/WtrLoo_Met/2005_weather_station_data.csv", col_names = T)%>%
#   select(2,3,4,7,8,9,10,11,12,13)%>%
#   mutate(minute = str_sub(Time, -2,-1),
#          hour = str_sub(Time, -4,-3),
#          hour = ifelse(hour == "", 0, hour))%>%
#   rename("year" =1, "DOY" = 2)%>%
#   mutate(datetime_raw = paste(year, DOY, hour, minute),
#          datetime = strptime(datetime_raw, "%Y %j %H %M"),
#          date = as.Date(datetime_raw, "%Y %j"))%>%
#   mutate(time = substr(as.POSIXct(sprintf("%04.0f", Time), format = "%H%M"),  12, 19))%>%
#   filter(time %in% c("12:00:00","12:15:00","12:30:00","12:45:00"))%>%
#   merge(., SN, by = "date")%>%
#   mutate(solarNoon = as.character(solarNoon))%>%
#   mutate(sn_minute = str_sub(solarNoon, 4,5),
#          time_minute = str_sub(time, 4,5),
#          sn_minute = as.numeric(sn_minute),
#          time_minute = as.numeric(time_minute),
#          sn_minute = sn_minute/60,
#          time_minute = time_minute/60,
#          sn_minute = as.numeric(str_sub(solarNoon, 1,2))+sn_minute,
#          time_minute = as.numeric(str_sub(time, 1,2))+time_minute,
#          time_diff = abs(time_minute - sn_minute))%>%
#   group_by(DOY)%>%
#   mutate(min_diff = min(time_diff))%>%
#   mutate(min_diff_filt = ifelse(min_diff == time_diff, 1, 0))%>%
#   filter(min_diff_filt == 1)%>%
#   select(1,3,16,17,5:11)%>%
#   rename("Hkin" = "Incoming Shortwave Radiation",
#          "Hkout" = "Reflected Shortwave Radiation",
#          "RH" = "Relative Humidity",
#          "Ta" = "Ambient Air Temperature", 
#          "Pa" = "Barometric Pressure",
#          "Udir" = "Wind Direction",
#          "Uz" = "Wind Speed")%>%
#   mutate(albedo = Hkout/Hkin)

```


### Waterloo Met Read In
```{r}
wtrloo_met_files <- list.files('data/WtrLoo_Met', full.names=T)

wtrloo_met_function <- function(file){
df <- read_csv(file = file, col_names = T)%>%
  select(2,3,4,7,8,9,10,11,12,13)%>%
  mutate(minute = str_sub(Time, -2,-1),
         hour = str_sub(Time, -4,-3),
         hour = ifelse(hour == "", 0, hour))%>%
  rename("year" =1, "DOY" = 2)%>%
  mutate(datetime_raw = paste(year, DOY, hour, minute),
         datetime = strptime(datetime_raw, "%Y %j %H %M"),
         date = as.Date(datetime_raw, "%Y %j"))%>%
  mutate(time = substr(as.POSIXct(sprintf("%04.0f", Time), format = "%H%M"),  12, 19))%>%
  filter(time %in% c("12:00:00","12:15:00","12:30:00","12:45:00"))%>%
  merge(., SN, by = "date")%>%
  mutate(solarNoon = as.character(solarNoon))%>%
  mutate(sn_minute = str_sub(solarNoon, 4,5),
         time_minute = str_sub(time, 4,5),
         sn_minute = as.numeric(sn_minute),
         time_minute = as.numeric(time_minute),
         sn_minute = sn_minute/60,
         time_minute = time_minute/60,
         sn_minute = as.numeric(str_sub(solarNoon, 1,2))+sn_minute,
         time_minute = as.numeric(str_sub(time, 1,2))+time_minute,
         time_diff = abs(time_minute - sn_minute))%>%
  group_by(DOY)%>%
  mutate(min_diff = min(time_diff))%>%
  mutate(min_diff_filt = ifelse(min_diff == time_diff, 1, 0))%>%
  filter(min_diff_filt == 1)%>%
  select(1,3,16,17,5:11)%>%
  rename("Hkin" = "Incoming Shortwave Radiation",
         "Hkout" = "Reflected Shortwave Radiation",
         "RH" = "Relative Humidity",
         "Ta" = "Ambient Air Temperature", 
         "Pa" = "Barometric Pressure",
         "Udir" = "Wind Direction",
         "Uz" = "Wind Speed")%>%
  mutate(albedo = Hkout/Hkin)

return(df)
}

wtrloo_met_data <- map_dfr(wtrloo_met_files, wtrloo_met_function)%>%
  filter(date >= "2005-09-01" & date <= "2013-08-31")

```

### Joined Met and Deoth, WtrLoo
```{r}
wtrloo_depth_met <- wtrloo_depth_all%>%
  merge(., wtrloo_met_data, by = "date", all = T)%>%
  mutate(SY = ifelse(date >= "2005-09-01" & date < "2006-09-01", "SY2006",
              ifelse(date >= "2006-09-01" & date < "2007-09-01", "SY2007",
              ifelse(date >= "2007-09-01" & date < "2008-09-01", "SY2008",
              ifelse(date >= "2008-09-01" & date < "2009-09-01", "SY2009",
              ifelse(date >= "2009-09-01" & date < "2010-09-01", "SY2010",
              ifelse(date >= "2010-09-01" & date < "2011-09-01", "SY2011",
              ifelse(date >= "2011-09-01" & date < "2012-09-01", "SY2012",
                     ifelse(date >= "2012-09-01" & date < "2013-09-01", "SY2013",NA)))))))))%>%
  mutate(DOSY = 1)%>%
  mutate(DOSY = ifelse(DOY > 243, DOY-243, DOY+122),
         DOSY = ifelse(SY == "SY2009" | SY == "SY2013",
                       ifelse(DOY > 244, DOY-244, DOY+122), DOSY),
         DOSY = ifelse(date == "2012-08-31" | date == "2008-08-31", 366, DOSY))%>%
  mutate(depth_m = depth_cm/100)%>%
  filter(!is.na(SY))


```

### Plots All Years
```{r}
ggplot(wtrloo_depth_met%>%filter(albedo<1 & albedo>0 & DOSY < 250), aes(x=date))+
  geom_line(aes(y=albedo), color = "gray45")+
  geom_line(aes(y=depth_cm/30), color = "steelblue2")+
  facet_wrap(~SY, ncol = 2, scales = "free_x")+
  theme_bw()+
  scale_y_continuous(name = "Albedo",
                     sec.axis = sec_axis(~.*30, name = "Depth (cm)"))+
   labs(title= "University of Waterloo Albedo vs Depth, SY(9/1-8/31)")

ggplot(wtrloo_depth_met%>%filter(albedo<1 & albedo>0 & DOSY < 250), aes(x=depth_cm))+
  geom_point(aes(y=albedo, color = DOSY))+
  facet_wrap(~SY, scales = "free_x")+
  theme_bw()
  
ggplot(wtrloo_depth_met%>%filter(depth_cm >0 & albedo<1 & albedo>0 & DOSY < 250), aes(x=depth_cm))+
  geom_point(aes(y=albedo, color = DOSY))+
  facet_wrap(~SY, scales = "free_x")+
  theme_bw()+
  scale_color_continuous(high = "gray0", low = "snow2")

```

### SY2006 - SY2010 Plots

```{r}
wtrloo_06_09 <- wtrloo_depth_met%>%
  filter(!SY %in% c("SY2011", "SY2012", "SY2013", "SY2010"))

ggplot(wtrloo_06_10%>%filter(albedo<1 & albedo>0 & DOSY < 250), aes(x=depth_m))+
  geom_point(aes(y=albedo, color = DOSY))+
  theme_bw()+
  scale_color_continuous(high = "gray0", low = "snow2")

ggplot(wtrloo_06_10%>%filter(albedo<1 & albedo>0 & DOSY < 250 & Hkout > 1), aes(x=date))+
  geom_line(aes(y=albedo), color = "gray45")+
  geom_line(aes(y=depth_cm/30), color = "steelblue2")+
  facet_wrap(~SY, ncol = 2, scales = "free_x")+
  theme_bw()+
  scale_y_continuous(name = "Albedo",
                     sec.axis = sec_axis(~.*30, name = "Depth (cm)"))+
   labs(title= "University of Waterloo Albedo vs Depth, SY(9/1-8/31)")


ggplot(wtrloo_06_09%>%filter(albedo<0.99 & albedo>0 & DOSY < 243 & Hkout > 1 & DOSY > 45), aes(x=date))+
  geom_line(aes(y=albedo), color = "gray45")+
  geom_line(aes(y=depth_m*3), color = "steelblue2")+
  facet_wrap(~SY, ncol = 2, scales = "free_x")+
  theme_bw()+
  scale_y_continuous(name = "Albedo",
                     sec.axis = sec_axis(~./3, name = "Depth (m)"))+
  labs(title= "University of Waterloo (10/15- 5/1)")+
  xlab(element_blank())+
  theme(text = element_text(size = 16, family = "Times New Roman"))


ggplot(wtrloo_06_09%>%filter(albedo<0.99 & albedo>0 & DOSY < 243 & Hkout > 1 & DOSY > 45), aes(x=depth_m))+
  geom_point(aes(y=albedo, color = DOSY))+
  facet_wrap(~SY, ncol = 2)+
  theme_bw()+
  ylab("Albedo")+
  labs(title= "University of Waterloo (10/15- 5/1)")+
  scale_color_gradient2(low = "gray10", mid = "snow3", high = "gray10", midpoint = 182)+
  xlab("Depth (m)")+
  theme(text = element_text(size = 16, family = "Times New Roman"))
  
```

### Depth at 0 and greater than 0
```{r}

ggplot(wtrloo_06_10%>%filter(albedo<0.99 & albedo >0 & DOSY < 243 & depth_cm > 0 & Hkout > 1), 
       aes(x=date))+
  geom_point(aes(y=albedo), color = "gray45")+
  geom_col(aes(y=depth_cm/30), fill = "steelblue2")+
  facet_wrap(~SY, ncol = 2, scales = "free_x")+
  theme_bw()+
  scale_y_continuous(name = "Albedo",
                     sec.axis = sec_axis(~.*30, name = "Depth (cm)"))+
   labs(title= "University of Waterloo Albedo vs Depth, SY(9/1-8/31)")

ggplot(wtrloo_06_10%>%filter(albedo<0.99 & albedo >0 & DOSY < 250 & depth_cm == 0 & Hkout > 1), 
       aes(x=date))+
  geom_point(aes(y=albedo), color = "gray45")+
  geom_col(aes(y=depth_cm/30), fill = "steelblue2")+
  facet_wrap(~SY, ncol = 2, scales = "free_x")+
  theme_bw()+
  scale_y_continuous(name = "Albedo",
                     sec.axis = sec_axis(~.*30, name = "Depth (cm)"))+
   labs(title= "University of Waterloo Albedo vs Depth, SY(9/1-8/31)")


```


### Closer look at depth

```{r}

ggplot(wtrloo_depth, aes(x=date, y=depth_cm))+
  geom_line()+
  facet_wrap(~year(date), scales= "free_x")+
  theme_bw()

wtrloo_depth_corr <- wtrloo_depth_met%>%
  rename("depth_wrng" = "depth_cm")%>%
  merge(., wtrloo_depth, by ="date")%>%
  select(1,14,2,17,6,7,13,12)


```

## Sky Conditions 
```{r}

# ktchnr_wtrloo <- read_csv("data/kitchenerwaterloo_daily.csv", col_names = T)
# names(ktchnr_wtrloo)
# clouds <- ktchnr_wtrloo%>%
#   select(1,59:62)%>%
#   mutate(date = ymd(date))
# 
# ggplot(clouds, aes(x=avg_hourly_cloud_cover_4, y=avg_cloud_cover_4))+
#   geom_point()+
#   geom_abline()
# 
# hist(clouds$avg_cloud_cover_4)
# hist(clouds$avg_hourly_cloud_cover_4)
# 
# clouds_2 <- clouds%>%
#   select(date, avg_hourly_cloud_cover_4)%>%
#   rename(cover = 2)%>%
#   mutate(perc_cover = cover/4)

lat = 43.473308
lat_rad = lat*(pi/180)
long = -80.557102
long_corr = ((long--75)/15)
names(wtrloo_depth_met)

wtrloo_zen <- wtrloo_depth_met%>%
  select(1,3,5,4)%>%
  rename("DOY" = DOY)%>%
  mutate(LST = time,
         LST = str_sub(LST, 1, 5),
         LST_dec = sapply(strsplit(LST, ":"),
                           function(t){
                             t <- as.numeric(t)
                             t[1]+t[2]/60}),
         LMT = LST_dec + long_corr)%>%
  mutate(day_angle = (2*pi*(DOY-1))/365,
         eccentricity = 1.000110 + 0.0342221*cos(day_angle)+
                        0.001280*sin(day_angle)+0.000719*cos(2*day_angle)+
                        0.000077*sin(2*day_angle),
         declination = 0.006918 - 0.399912*cos(day_angle)+ 0.070257*sin(day_angle)-
                       0.006758*cos(2*day_angle) + 0.000907*sin(2*day_angle)-
                       0.002697*cos(3*day_angle) + 0.00148*sin(3*day_angle),
         eq_of_time = 0.000292 + 0.007264*cos(day_angle) - 0.12474*sin(day_angle)-
                      0.05684*cos(2*day_angle) - 0.15886*sin(2*day_angle))%>%
  mutate(LAT = LMT + eq_of_time,
         t_sn = LAT - 12)%>% ### standard reading of 12 as in noon
  mutate(minute_time = as.numeric(str_sub(time, 4, 5))/60,
         minute_sn = as.numeric(str_sub(solarNoon,4,5))/60,
         t_sn_2 = minute_time - minute_sn)%>% ### solarnoon found from suncalc  
  mutate(zenith_angle = acos(cos(declination)*cos(lat_rad)*cos(0.2618*t_sn)+
                               sin(declination)*sin(lat_rad)),
         zenith_angle_2 = acos(cos(declination)*cos(lat_rad)*cos(0.2618*t_sn_2)+
                               sin(declination)*sin(lat_rad)),
         zenith_deg = zenith_angle*(180/pi),
         zenith_deg_2 = zenith_angle_2*(180/pi))%>%
  merge(., clouds_2, by = "date")%>%
  mutate(Hkin = 1367*eccentricity*cos(zenith_angle)*(0.355+0.68*(1-perc_cover)),
         Hkin_2 = 1367*eccentricity*cos(zenith_angle_2)*(0.355+0.68*(1-perc_cover)))

# ggplot(wtrloo_zen, aes(x=perc_cover, y = Hkin))+
#   geom_point()
# ggplot(wtrloo_zen, aes(x=Hkin_2, y = Hkin))+
#    geom_point()

ggplot(wtrloo_zen, aes(x=t_sn, y=t_sn_2))+
  geom_point()
ggplot(wtrloo_zen, aes(x=zenith_angle, y=zenith_angle_2))+
  geom_point()


```

### Modeled Hkin Albedo

```{r}

wtrloo_hkin <- wtrloo_zen%>%
  select(1,11)%>%
  rename("Hkin_mod" = 2)

wtrloo_model <- merge(wtrloo_depth_met, wtrloo_hkin, by = "date")%>%
  mutate(alb_model = Hkout/Hkin_mod)%>%
  mutate(alb_final = ifelse(albedo > 1 & albedo < 1 & !is.na(alb_model), alb_model, albedo))

```

```{r}
ggplot()
```


